---
title: "Analytics"
output: md_document
params:
  healthRisk: "AWD"
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
knitr::opts_chunk$set(echo = F)

map <- readRDS("data/gadm36_NOR_1_sp.rds")
  #map <- rmapshaper::ms_simplify(map,keep = 0.5)
map <- broom::tidy(x=map,region="NAME_1")
setDT(map)
unique(map$id)
#saveRDS(map,"data/map_supervisor.RDS")


WeekC <- function (date = lubridate::today()) 
{
    wk <- as.numeric(format.Date(date, "%V"))
    wk <- formatC(wk, flag = "0", width = 2)
    return(wk)
}

Year <- function (date = lubridate::today()) 
{
    yr <- as.numeric(format.Date(date, "%G"))
    return(yr)
}

YearWeek <- function(date){
  return(sprintf("%s-%s", Year(date), WeekC(date)))
}

YearWeekN <- function(date){
  return(as.numeric(sprintf("%s%s", Year(date), WeekC(date))))
}

dr <- readxl::read_excel("data/casereports-2018-September-28 (1).xlsx")
dc <- readxl::read_excel("data/datacollectors-2018-September-28 (1).xlsx")

setDT(dr)
setDT(dc)


setnames(dr,"Data Collector","datacollector")
setnames(dr,"Males < 5","mu5")
setnames(dr,"Males ≥ 5","mo5")
setnames(dr,"Females < 5","fu5")
setnames(dr,"Females ≥ 5","fo5")

dr <- rbind(dr,dr,dr,dr,dr)

dr[,n:=floor(1:.N/2),by=datacollector]
dr[,Date:=lubridate::today()-n]
dr[,n:=NULL]

dr <- dr[`Health Risk`==params$healthRisk]
dr[,`Health Risk`:=NULL]
setnames(dr,"Lat. / Long.","latlong")

dr[,Region:=NULL]
dr[,District:=NULL]
dr[,Village:=NULL]
dr[,latlong:=NULL]

locs <- dc[,c("Display Name","Lat. / Long.","Region","District","Village")]
setnames(locs,c("datacollector","latlong","region","district","village"))


minDate <- min(dr$Date)
maxDate <- max(dr$Date)
weeks <- data.table(Date=seq.Date(minDate,maxDate,1))
weeks[,rollingWeek:=floor(as.numeric(difftime(max(Date),Date,units="days"))/7)]
weeks[,epiWeek:=YearWeek(Date)]
weeks[,epiWeekN := YearWeekN(Date)]
weeks[,rollingMinDate:=min(Date),by=rollingWeek]
weeks[,rollingMaxDate:=max(Date),by=rollingWeek]
weeks[,epiMinDate:=min(Date),by=epiWeek]
weeks[,epiMaxDate:=max(Date),by=epiWeek]
weeks[,rollingx:=max(rollingWeek)-rollingWeek]
weeks[,epix:=max(epiWeekN)-epiWeekN]

weeksNoDate <- copy(weeks)
weeksNoDate[,Date:=NULL]
weeksNoDate <- unique(weeksNoDate)

skeleton <- vector("list",length=nrow(locs))
for(i in 1:nrow(locs)){
  skeleton[[i]] <- copy(weeks)
  skeleton[[i]][,datacollector:=locs$datacollector[i]]
}
skeleton <- rbindlist(skeleton)
nrow(skeleton)
skeleton <- merge(skeleton,locs,by=c("datacollector"),all.x=T,allow.cartesian = T)
nrow(skeleton)
d <- merge(skeleton,dr,by=c("Date","datacollector"),all.x=T,allow.cartesian = T)
nrow(d)
d[,isMessage:=ifelse(is.na(Time),0,1)]
xtabs(~d$isMessage)

d[is.na(mu5),mu5:=0]
d[is.na(mo5),mo5:=0]
d[is.na(fu5),fu5:=0]
d[is.na(fo5),fo5:=0]

n <- names(d)[!names(d) %in% c("mu5","mo5","fu5","fo5")]
d <- melt.data.table(d,id.vars=n)

d[,sex:="Male"]
d[variable %in% c("fu5","fo5"),sex:="Female"]

d[,age:="Age <5"]
d[variable %in% c("mo5","fo5"),age:="Age 5+"]

```



## Epicurve by week

```{r message=FALSE, warning=FALSE}
toplot <- d[,.(n=sum(value)),by=.(epiWeek)]

q <- ggplot(toplot,aes(x=epiWeek,y=n))
q <- q + geom_col()
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
q
```

## Epicurve by day dodge

```{r message=FALSE, warning=FALSE}
toplot <- d[,.(n=sum(value)),by=.(Date,age)]

q <- ggplot(toplot,aes(x=Date,y=n,fill=age))
q <- q + geom_col(pos="dodge")
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
#q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
q
```

## Epicurve by week dodge

```{r message=FALSE, warning=FALSE}
toplot <- d[,.(n=sum(value)),by=.(epiWeek,age)]

q <- ggplot(toplot,aes(x=epiWeek,y=n,fill=age))
q <- q + geom_col(pos="dodge")
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
q
```

## Age and sex distribution

```{r message=FALSE, warning=FALSE}
toplot <- d[epiWeek==max(epiWeek),.(n=sum(value)),by=.(epiWeek,age,sex)]

q <- ggplot(toplot,aes(x=age,y=n))
q <- q + geom_col()
q <- q + labs(title=sprintf("Age and sex distribution %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Age")
q <- q + scale_y_continuous("Number of alerts")
q <- q + facet_grid(.~sex)
q <- q + coord_flip()
q
```

## Epicurve by age/sex

```{r message=FALSE, warning=FALSE}
toplot <- d[,.(n=sum(value)),by=.(epiWeek,sex,age)]

q <- ggplot(toplot,aes(x=epiWeek,y=n))
q <- q + geom_col()
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + facet_grid(sex~age)
q
```

## Epicurve by district

```{r message=FALSE, warning=FALSE}
toplot <- d[,.(n=sum(value)),by=.(epiWeek,district)]

q <- ggplot(toplot,aes(x=epiWeek,y=n))
q <- q + geom_col()
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + facet_wrap(~district)
q <- q + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
q
```

## Map by district

```{r message=FALSE, warning=FALSE}
toplot <- d[epiWeek==max(epiWeek),.(n=sum(value)),by=.(epiWeek,district)]
m <- merge(map,toplot,by.x="id",by.y="district",all.x=T)
b <- unique(quantile(m$n,na.rm=T))
m[,fillVal:=cut(n,breaks = b)]
l <- levels(m$fillVal)
m[,fillVal:=as.character(fillVal)]
m[is.na(fillVal),fillVal:="Not reporting"]
m[,fillVal:=factor(fillVal,levels=c("Not reporting",l))]

q <- ggplot()
q <- q + geom_map(data = m, aes(x = long, y = lat, map_id = id, fill=fillVal),
map = m, colour = "black", size=0.1)
q <- q + coord_map("albers",  at0 = 45.5, lat1 = 29.5)
q <- q + scale_fill_manual("",values=c("grey","#ffffb2","#fecc5c","#fd8d3c","#e31a1c"),drop=F)
q <- q + scale_x_continuous("")
q <- q + scale_y_continuous("")
q <- q + labs(title="Cases in epiweek X")
q
```

## Barcharts by district

```{r message=FALSE, warning=FALSE}
toplot <- d[epiWeek==max(epiWeek),.(n=sum(value)),by=.(epiWeek,district)]

q <- ggplot(toplot,aes(x=district,y=n))
q <- q + geom_col()
q <- q + labs(title=sprintf("Epicurve from %s to %s",minDate,maxDate))
q <- q + labs(caption=sprintf("Created %s",lubridate::today()))
q <- q + scale_x_discrete("Epiweek")
q <- q + scale_y_continuous("Number of alerts")
q <- q + coord_flip()
q <- q + labs(title="Cases in epiweek X")
#q <- q + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5))
q
```


