kind: PersistentVolume
apiVersion: v1
metadata:
  name: device-events
  labels:
    type: local
    name: device-events
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/deviceEvents"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: eventstore
  labels:
    type: local
    name: eventstore
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/eventStore"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: readmodels
  labels:
    type: local
    name: readmodels
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/readModels"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka
  labels:
    type: local
    name: kafka
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper
  labels:
    type: local
    name: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/zookeeper"