kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: device-events
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: device-events
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eventstore
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: eventstore
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readmodels
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: readmodels
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: kafka
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: zookeeper


      