# Todo: Password for logs

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana
spec:
  template:
    metadata:
      labels:
        app: logging
        name: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 3000
        env:
#        volumeMounts:
#        - mountPath: "/var/lib/grafana"
#          name: datadir
#      volumes:
#      - name: datadir
#        persistentVolumeClaim:
#          claimName: grafana
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
spec:
  template:
    metadata:
      labels:
        app: logging
        name: elasticsearch
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        - name: cluster.name
          value: "smartrope"
        - name: bootstrap.memory_lock
          value: "true"
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: datadir
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: elasticsearch
