kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: grafana
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: elasticsearch
