version: '3'
networks:
  cbs-network:
services:
  cbs-analytics-core:
    image: redcrossredcrescent/cbs-analytics-backend:latest
    build:
      context: "../../"
      dockerfile: "Source/Analytics/Web/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SWAGGER_PREFIX=swagger/analytics/
      - SWAGGER_BASE_PATH=analyticsbackend/
    volumes:
      - "./cbs-tenants.json:/CBS/Web/.dolittle/tenants.json"
      - "./cbs-tenant-map.json:/CBS/Web/.dolittle/tenant-map.json"
      - "./cbs-analytics-resources.json:/CBS/Web/.dolittle/resources.json"
      - "./cbs-analytics-event-horizons.json:/CBS/Web/.dolittle/event-horizons.json"
    networks:
      - "cbs-network"

  cbs-reporting-web:
    image: redcrossredcrescent/cbs-analytics-frontend:latest
    build:
      context: "../../Source/"
      dockerfile: "Analytics/Web.Frontend/Dockerfile"
      args:
        mode: "build-test"
    expose:
      - "80"
    networks:
      - "cbs-network"