version: '3'
networks:
  cbs-network:
services:
  cbs-ingress-nginx:
    image: "nginx:1.15-alpine"
    ports:
      - "8080:8080"
    volumes:
      - "./shared-nginx-default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - "cbs-network"

  cbs-db-mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - "cbs-network"